### ISSUE TITLE
Donations page ~ PayPal link over Credit Card button!

### ISSUE THREAD

**Issue by cowcreekgeek** [creativecommons/creativecommons.org#463]
Instead of an alternative BUTTON for PayPal? The page produce a barely visible link directly over the button to submit credit card payment, making either method of payment difficult. 

Also, there are nissing images, and no return. 

Issue occurs w/ both Firefox and default (early chrome) browsers, on android 6.0. 

Yes, my donation did still go through ~;-)

**Comment by robmyers** [comment]
This is on https://creativecommons.org/donate and also appears on staging.

To reproduce:

1. Select a five dollar monthly donation and click "Next".
2. Enter dummy values for name and address and click "Next".
3. Scroll down to the "Submit" button. Note that the PayPal link is placed over the "Submit" arrow.

**Comment by robmyers** [comment]
@ageeroms I'm not sure if this is breakage from my updating Gravity Forms or WordPress or what the cause is but it's present on both live and staging. Please can you take a look?

**Comment by ageeroms** [comment]
![screen shot 2016-10-05 at 12 56 43 pm](https://cloud.githubusercontent.com/assets/6674702/19129200/3ce680ca-8afb-11e6-8316-46fd908f5468.png)

@altrugon can you please take a look at this? See steps above to reproduce and is only on mobile width. Please submit a pull request with fix.

**Comment by ageeroms** [comment]
Hey @robmyers , Alberto gave this solution:

    Branch issue-463-paypal_link_overlap set up to track remote branch issue-463-paypal_link_overlap from origin.
    ~/Sites/creativecommons/wp-content/themes/cc (issue-463-paypal_link_overlap)$ git remote -v
    origin	git@github.com:creativecommons/new-www-theme.git (fetch)
    origin	git@github.com:creativecommons/new-www-theme.git (push)

Could you pull that onto Staging and take a look to see if that fixes the issue? 

Thanks!

**Comment by cowcreekgeek** [comment]
Error in placement of paypal-toggle on page #gf_3 only occurs in narrow
viewports, but in all browsers I've tested -- just used it to make another
donation, but still interferes with credit card input.

In your cc-donate.css file, padding is applied to the class paypal-toggle,
which is also positioned absolutely on wider screens ... that might be a
good place to make temporary adjustment(s), even if not the actual cause of
the error(s).

While you're in there? You could throw PayPal's donate button colors onto
the link's text as well: Supernova (#ffae33) and Peach Yellow (#fbdfac)
should stand out much better on your background.

Thank you for helping them, as they continue to help us all ...

d@niel / cowcreekgeek ~;-)

**Comment by robmyers** [comment]
@geeroms I've put issue-463-paypal_link_overlap on staging and the problem still seems to be there for really narrow viewports (e.g. my Android phone browser).

**Comment by ageeroms** [comment]
@altrugon , Rob put your fix on https://staging.creativecommons.org and I'm still seeing the issue on narrow viewports, e.g. Galaxy 7.

**Comment by altrugon** [comment]
@robmyers I've merged _master_ into _issue-463-paypal_link_overlap_ and continued working there to avoid the creation of a new branch.

It seems that I was missing to remove a "position absolute" from the Paypay payment link on the mobile layout, I have added that line of code and pushed it to the repo.

**Comment by cowcreekgeek** [comment]
@altrugon The absolute positioning was part of the issue, but the overlap still occurs on narrow viewports because the green "submit" button is pushed beneath the "back" button, which the PayPal link appears to positioned relative to.

Links work (can't look w/o donating ~;-)

Allowing for the height of that button when the viewport become narrow saves me money.

**Comment by altrugon** [comment]
My [last commit](https://github.com/creativecommons/new-www-theme/commit/8a9231aafc64d6711fdcbb232d2834c5f9b92f97) on this branch was never merged, that's the reason because the overlap still exist.

At this point this branch is 45 commits behind and there is also [ticket 556](https://github.com/creativecommons/creativecommons.org/issues/556) complaining of the same problem, so I'm closing this ticket and its branch and moving all the remaing work into ticket 556.
